name: Publish package to GitHub Packages

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          registry-url: https://npm.pkg.github.com
          scope: "@couchbaselabs"

      - run: bun install
      - run: bun run build
      - run: bun publish
        env:
          BUN_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}